# Generated by Django 2.0.5 on 2018-05-08 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 8, 11, 1, 50, 615700)),
        ),
    ]
