# Generated by Django 2.0.5 on 2018-05-08 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='added',
        ),
        migrations.AddField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 8, 11, 22, 1, 61469)),
        ),
    ]
