# Generated by Django 2.0.5 on 2018-07-13 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20180508_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 13, 10, 49, 24, 532028)),
        ),
    ]
